import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // 默认的自动生成侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // tutorialSidebar: [
  //   // 这是一个普通的文档链接
  //   'intro',

  //   // =========== 这里是重点：添加分隔符 ===========
  //   {
  //     type: 'html',
  //     value: '<span class="sidebar-divider">______________</span>', // 这里写你的标题
  //     defaultStyle: true, // 使用默认样式（如果不满意可以自己写CSS）
  //   },
  //   // ============================================

    
  //   // =========== 又一个分隔符 ===========
  //   {
  //     type: 'html',
  //     value: '<span class="sidebar-divider">______________</span>', 
  //     defaultStyle: true,
  //   },
  //    {
  //     type: 'category',
  //     label: '🚀 快速开始',  // 用 emoji 图标让标签更生动
  //     collapsible: true,     // 可折叠
  //     collapsed: false,      // 默认展开（漂亮点，让用户一眼看到内容）
  //     className: 'sidebar-category-quickstart',  // 自定义 class，用于 CSS 针对美化
  //     items: [ 
  //       // 文件夹下的文档列表,优先级最高,其次是docs目录下的_category.json,最低是md的元数据
  //       'tutorial-basics/create-a-document',
  //       'tutorial-basics/create-a-page',
  //       'tutorial-basics/create-a-blog-post',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '📚 基础教程',
  //     collapsible: true,
  //     collapsed: true,  // 默认折叠，避免一开始太长
  //     items: [
  //       'tutorial-basics/deploy-your-site',
  //       'tutorial-basics/markdown-features',
  //     ],
  //   },
  //   {
  //     type: 'category',
  //     label: '⚙️ 高级特性',
  //     collapsible: true,
  //     collapsed: true,
  //     items: [
  //       'tutorial-extras/manage-docs-versions',
  //       'tutorial-extras/translate-your-site',
  //     ],
  //   },
  // ],
};

export default sidebars;
