import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  javaSidebar: [ // 注意这个名字，Navbar 里要用
    {
      type: 'autogenerated',
      dirName: '.', // 自动扫描 docs-java 文件夹
    },
  ],
};
export default sidebars;