import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  pythonSidebar: [ // 注意这个名字
    {
      type: 'autogenerated',
      dirName: '.', // 自动扫描 docs-python 文件夹
    },
  ],
};
export default sidebars;